
// Meet Rjali

IF
  G("Rjali1Met",0)
  Gender(Player1,MALE)
  !Alignment(Player1,MASK_EVIL)
THEN
  RESPONSE #100
    SetGlobal("RjaliLamp","GLOBAL",1)
    Continue()
END

IF
  G("Chapter",0)
  G("Rjali1Met",0)
THEN
  RESPONSE #100
    CreateCreature("RJGREG",[1162.671],8)
    CreateCreature("RJALIY",[1212.635],8)
    ActionOverride(Player1,ChangeAIScript("RJPLAYER",OVERRIDE))
    SetGlobal("Rjali1Met","GLOBAL",1)
    Continue()
END
