
IF
  True()
THEN
  RESPONSE #100
    CutSceneID(Player1)
    FadeToColor([30.0],0)
    Wait(1)
    ActionOverride("RJFAY1",Polymorph(WILL_O_WISP_SMALL))
    BanterBlockFlag(FALSE)
    SetGlobal("RJiniTalk","GLOBAL",0)
    SetGlobal("RJPort","GLOBAL",0)
    RestorePartyLocations()
    Wait(3)
    FadeFromColor([20.0],0)
    Wait(3)
    DisplayStringHead("RJFAY1",@209)
    Wait(3)
    EndCutSceneMode()
END
